### ISSUE TITLE
 Error in rule join_propagate

### ISSUE THREAD

**Issue by sauveer** [commonsense/conceptnet5#213]
Hi,

I get the following error when the build executes the jobid: 24

P.S.: I am running this command as sudo and have also given the snakemake files execution rights i.e. chmod 777:

-----------------------------------------------------------------------------------------------------------------
    Error in rule join_propagate:
        jobid: 24
        output: data/vectors/numberbatch-biased.h5

Traceback (most recent call last):
  File "/home/sopra/.local/lib/python3.5/site-packages/snakemake/executors.py", line 344, in _callback
    callback(job)
  File "/home/sopra/.local/lib/python3.5/site-packages/snakemake/scheduler.py", line 323, in _proceed
    self.get_executor(job).handle_job_success(job)
  File "/home/sopra/.local/lib/python3.5/site-packages/snakemake/executors.py", line 357, in handle_job_success
    super().handle_job_success(job)
  File "/home/sopra/.local/lib/python3.5/site-packages/snakemake/executors.py", line 151, in handle_job_success
    assume_shared_fs=self.assume_shared_fs)
  File "/home/sopra/.local/lib/python3.5/site-packages/snakemake/jobs.py", line 840, in postprocess
    ignore_missing_output=ignore_missing_output)
  File "/home/sopra/.local/lib/python3.5/site-packages/snakemake/dag.py", line 371, in check_and_touch_output
    f.touch()
  File "/home/sopra/.local/lib/python3.5/site-packages/snakemake/io.py", line 366, in touch
    raise e
  File "/home/sopra/.local/lib/python3.5/site-packages/snakemake/io.py", line 357, in touch
    lutime(self.file, times)
  File "/home/sopra/.local/lib/python3.5/site-packages/snakemake/io.py", line 38, in lutime
    os.utime(f, times, follow_symlinks=False)
PermissionError: [Errno 13] Permission denied

**Comment by rspeer** [comment]
I don't know what exactly happened to your permissions, but our build instructions don't involve running as `sudo`.

Please run the ConceptNet build as a user who owns both the Python environment (in your case, this is `/home/sopra/.local/lib/python3.5`) and the files in the `data/` directory. Don't let anything be owned by root, and don't sudo (except to undo what you've done as root).

If you can't recover user ownership of your local python3.5 environment, I recommend setting up a new environment using 
[virtualenv](https://packaging.python.org/guides/installing-using-pip-and-virtualenv/). virtualenv is pretty much the standard for local Python development; anything you do that's not in a virtualenv is at your own risk.

**Comment by sauveer** [comment]
Hi,

Assigning the execution permissions to the library, it worked!!,

also I got an error in the rule load_db:

-----------------------------------------------------------------------------------------------
rule load_db:
    input: data/psql/edges.csv, data/psql/edge_sources.csv, data/psql/edge_features.csv, data/psql/nodes.csv, data/psql/node_prefixes.csv, data/psql/sources.csv, data/psql/relations.csv
    output: data/psql/done
    jobid: 2

Traceback (most recent call last):
  File "/usr/local/bin/cn5-db", line 11, in <module>
    load_entry_point('ConceptNet', 'console_scripts', 'cn5-db')()
  File "/home/sopra/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sopra/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sopra/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sopra/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sopra/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sopra/conceptnet5/conceptnet5/db/cli.py", line 23, in load_data
    create_tables(conn)
  File "/home/sopra/conceptnet5/conceptnet5/db/schema.py", line 90, in create_tables
    run_commands(connection, TABLES)
  File "/home/sopra/conceptnet5/conceptnet5/db/schema.py", line 85, in run_commands
    cursor.execute(cmd)
psycopg2.InternalError: cannot drop table nodes because other objects depend on it
DETAIL:  constraint edges_start_id_fkey on table edges depends on table nodes
constraint edges_end_id_fkey on table edges depends on table nodes
constraint node_prefixes_node_id_fkey on table node_prefixes depends on table nodes
constraint node_prefixes_prefix_id_fkey on table node_prefixes depends on table nodes
constraint edge_features_node_id_fkey on table edge_features depends on table nodes
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

    Error in rule load_db:
        jobid: 2
        output: data/psql/done

RuleException:
CalledProcessError in line 429 of /home/sopra/conceptnet5/Snakefile:
Command ' set -euo pipefail;  cn5-db load_data data/psql && touch data/psql/done ' returned non-zero exit status 1
  File "/home/sopra/conceptnet5/Snakefile", line 429, in __rule_load_db
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run

**Comment by rspeer** [comment]
Weird. It's trying to reset the database and it's supposed to drop database tables in the right order; I don't know why it's complaining about dependencies that should already be gone. But you can force the issue and create a fresh database, by running these commands at the command line:

    dropdb conceptnet5
    createdb conceptnet5

**Comment by sauveer** [comment]
Hi,

This worked perfectly for me..many thanks for the help :)

**Comment by rspeer** [comment]
Great to hear!
