### ISSUE TITLE
how to give the access right to  'conceptnet5'  PostgreSQL database

### ISSUE THREAD

**Issue by loveJasmine** [commonsense/conceptnet5#228]
I had done:

ub16hp@UB16HP:~/ub16_prj/conceptnet-numberbatch$ sudo -i -u postgres
[sudo] password for ub16hp: 
postgres@UB16HP:~$ psql
psql (9.5.14)
Type "help" for help.

postgres=# createdb conceptnet5

then:
ub16hp@UB16HP:~/ub16_prj/conceptnet5$ sudo bash build.sh 
df: data: No such file or directory
build.sh: line 6: [: -lt: unary operator expected
The directory '/home/ub16hp/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If
........
.......
Successfully installed ConceptNet
Traceback (most recent call last):
  File "/usr/local/bin/cn5-db", line 9, in <module>
    load_entry_point('ConceptNet', 'console_scripts', 'cn5-db')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ub16hp/ub16_prj/conceptnet5/conceptnet5/db/cli.py", line 30, in run_check_db_connection
    check_db_connection()
  File "/home/ub16hp/ub16_prj/conceptnet5/conceptnet5/db/connection.py", line 54, in check_db_connection
    _get_db_connection_inner(dbname)
  File "/home/ub16hp/ub16_prj/conceptnet5/conceptnet5/db/connection.py", line 36, in _get_db_connection_inner
    conn = psycopg2.connect(dbname=dbname)
  File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "root" does not exist

You don't have access to the 'conceptnet5' PostgreSQL database.
You may need to install PostgreSQL 9.5 or later, create this database,
give yourself access to it, or set $CONCEPTNET_DB_NAME to a database
that you can use.
ub16hp@UB16HP:~/ub16_prj/conceptnet5$ 

how

**Comment by loveJasmine** [comment]
not very clear, but make it pass by:
postgres-# createuser --interactive
postgres-# psql
postgres-# createuser root
postgres-# q
postgres-# \q
postgres@UB16HP:~$ createuser --interactive
Enter name of role to add: root
Shall the new role be a superuser? (y/n) y
postgres@UB16HP:~$ 
postgres@UB16HP:~$ createuser --interactive
Enter name of role to add: conceptnet5
Shall the new role be a superuser? (y/n) y
postgres@UB16HP:~$ exit
logout
ub16hp@UB16HP:~$ sudo -i -u test1
sudo: unknown user: test1
sudo: unable to initialize policy plugin
ub16hp@UB16HP:~$ sudo -i -u root
root@UB16HP:~# psql
psql: FATAL:  database "root" does not exist
root@UB16HP:~# psql -d conceptnet5
psql: FATAL:  database "conceptnet5" does not exist
root@UB16HP:~# createdb conceptnet5
root@UB16HP:~# psql -d conceptnet5
psql (9.5.14)
Type "help" for help.

conceptnet5=#
