### ISSUE TITLE
error during building coneptnet

### ISSUE THREAD

**Issue by JohannaOm** [commonsense/conceptnet5#280]
Hello,
I am trying to build ConceptNet and currently get an error in the miniaturize rule.
The error is listed below.
Does anyone know why this error occurs and how I can fix it?

```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wordfreq/__init__.py", line 281, in word_frequency
    return _wf_cache[args]
KeyError: ('##', 'zh', 'best', 0.0)'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/cn5-vectors", line 11, in <module>
    load_entry_point('ConceptNet', 'console_scripts', 'cn5-vectors')()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/work/conceptnet5/vectors/cli.py", line 288, in run_miniaturize
    mini = miniaturize(frame, other_vocab=other_vocab, k=k)
  File "/work/conceptnet5/vectors/miniaturize.py", line 51, in miniaturize
    term for term in frame.index if '_' not in term and term_freq(term) >= 1e-8
  File "/work/conceptnet5/vectors/miniaturize.py", line 51, in <listcomp>
    term for term in frame.index if '_' not in term and term_freq(term) >= 1e-8
  File "/work/conceptnet5/vectors/miniaturize.py", line 25, in term_freq
    return wordfreq.word_frequency(term, lang)
  File "/usr/local/lib/python3.7/dist-packages/wordfreq/__init__.py", line 285, in word_frequency
    _wf_cache[args] = _word_frequency(*args)
  File "/usr/local/lib/python3.7/dist-packages/wordfreq/__init__.py", line 228, in _word_frequency
    tokens = lossy_tokenize(word, lang)
  File "/usr/local/lib/python3.7/dist-packages/wordfreq/tokens.py", line 278, in lossy_tokenize
    tokens = tokenize(text, lang, include_punctuation, external_wordlist)
  File "/usr/local/lib/python3.7/dist-packages/wordfreq/tokens.py", line 237, in tokenize
    from wordfreq.chinese import jieba_tokenize as _jieba_tokenize
  File "/usr/local/lib/python3.7/dist-packages/wordfreq/chinese.py", line 9, in <module>
    SIMPLIFIED_MAP = msgpack.load(gzip.open(SIMP_MAP_FILENAME), raw=False)
  File "/usr/local/lib/python3.7/dist-packages/msgpack/__init__.py", line 46, in unpack
    return unpackb(data, **kwargs)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: int is not allowed for map key
Error in rule miniaturize:
    jobid: 9
    output: data/vectors/mini.h5
    shell:
        cn5-vectors miniaturize data/vectors/numberbatch-biased.h5 data/vectors/w2v-google-news.h5 data/vectors/mini.h5
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)```

**Comment by rspeer** [comment]
Can you repost and surround the output with three backticks, instead of one, so that it preserves linebreaks?

**Comment by rspeer** [comment]
Actually -- given that the output involves wordfreq and msgpack, I suspect it's this version incompatibility that just showed up between them: https://github.com/LuminosoInsight/wordfreq/blob/master/CHANGELOG.md#version-222-2020-02-28

So try updating to wordfreq 2.2.2:

    pip install --upgrade wordfreq

**Comment by JohannaOm** [comment]
Many thanks for the rush answer!
That solved my problem.
