### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by chris-hawley** [commonsense/conceptnet5#75]
I was trying to build the data and got the following error message. 

Traceback (most recent call last): 
  File "/usr/local/bin/cn5-vectors", line 9, in <module>
    load_entry_point('ConceptNet==5.5.1', 'console_scripts', 'cn5-vectors')()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __ call __
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/mnt/e/conceptnet/conceptnet5/conceptnet5/vectors/cli.py", line 83, in run_intersect
    intersected, projection = merge_intersect(frames)
  File "/mnt/e/conceptnet/conceptnet5/conceptnet5/vectors/merge.py", line 32, in merge_intersect
    joined = pd.concat(frames, join='inner', axis=1, ignore_index=True).astype('f')
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/generic.py", line 3054, in astype
    raise_on_error=raise_on_error, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/internals.py", line 3189, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/internals.py", line 3012, in apply
    self._consolidate_inplace()
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/internals.py", line 3529, in _consolidate_inplace
    self.blocks = tuple(_consolidate(self.blocks))
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/internals.py", line 4521, in _consolidate
    _can_consolidate=_can_consolidate)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/internals.py", line 4544, in _merge_blocks
    new_values = new_values[argsort]
MemoryError

**Comment by rspeer** [comment]
How much RAM does your system have? How much of it was available at the time?

Were you building inside Docker, or using your own Python installation?

Are you running on a 64-bit OS?

**Comment by chris-hawley** [comment]
My system has 16 GB of ram. I'm not exactly sure how much was being used by other processes at the time but I normally have around 4 GB used by background applications. I'm running on windows 10 64-bit. I was building inside docker then when I got that error, I tried again with bash using the longer method and it still failed. I also tried limiting snakemake to 8 GB of ram and that failed as well.

**Comment by chris-hawley** [comment]
I will also add that my page file bloomed to 50gb when running it under bash

**Comment by rspeer** [comment]
Hm, got it. Something is using much more memory simultaneously than I expected, and it might be the fault of a recent change to the Snakemake instructions.

Have you tried limiting Snakemake to only a single process at a time (`-j 1`), in case instructing it to limit its simultaneous RAM usage is not accurate enough?

A workaround: you could make the `webdata` target instead of `all` in Snakemake, which skips building the vector space, and if you need the vector space you can instead retrieve it from https://github.com/commonsense/conceptnet-numberbatch .

**Comment by chris-hawley** [comment]
The only reason I'm trying to build the data myself is so I can host my own database/api site.  I will try limiting Snakemake to one thread and get back to you. It might be a few days before I get around to that since I will be traveling for the holidays.

**Comment by rspeer** [comment]
In that case, definitely just build `webdata` (snakemake webdata). The part that eats all the RAM is making the vectors.

Or, if you run it through docker-compose, the Dockerfile for the `data-loader` container should skip the build and just download the files it needs.

**Comment by chris-hawley** [comment]
I am rebuilding it right now. I am starting it out fresh to ensure that there will not be any other factors affecting the build process.

**Comment by chris-hawley** [comment]
Interestingly enough, `snakemake webdata -j 1` did not limit the threads to 1 or only build webdata. It failed again on generating the vectorspace.

**Comment by chris-hawley** [comment]
I got the information added to my database. I had to manually execute the necessary commands and change a few lines in the python scripts. Most of those changes were likely due to WSL not liking some things.

**Comment by rspeer** [comment]
This may be a bug in a recent version of Snakemake. I notice that Snakemake 3.7.1, for me, seems to be ignoring resource limits that it's given on the command line.
